modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
modId="yeeter"
version="${file.jarVersion}"
displayName="TNT Yeeter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-yeeter"
updateJSONURL="http://changelogs.moddinglegacy.com/tnt-yeeter.json"
logoFile="tnt-yeeter.png"
credits="Thanks to Lachney, Jesterguy, Vamacher0n AndyPyr0, JoltLiz, eddieb, catheldrin, calaquarium, and unpiggie for contributing their voices to the TNT Yeeter."
authors="Modding Legacy, KingPhygieBoo, Lachney"
description='''
Adds a TNT Yeeter mob inspired by Reddit post https://www.reddit.com/r/Minecraft/comments/cq0mgn/i_made_a_tnt_yeeter/
'''
[[dependencies.yeeter]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yeeter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
