modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://gitlab.com/modding-legacy/yeet/issues"
[[mods]]
modId="yeeter"
version="${file.jarVersion}"
displayName="TNT Yeeter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-yeeter"
updateJSONURL="https://gitlab.com/modding-legacy/supporters/-/raw/master/tnt-yeeter.json"
logoFile="tnt-yeeter.png"
credits="Thanks to Lachney, Jesterguy, and Vamacher0n for contributing their voices to the TNT Yeeter."
authors="Modding Legacy, KingPhygieBoo, Lachney"
description='''
Adds a TNT Yeeter mob inspired by Reddit post https://www.reddit.com/r/Minecraft/comments/cq0mgn/i_made_a_tnt_yeeter/
'''
[[dependencies.yeeter]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yeeter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
